name: locale_gen
description: Dart tool that will convert your default locale json to dart code.
version: 12.1.3
homepage: https://github.com/impaktfull/flutter_locale_gen
environment:
  sdk: ">=3.0.0 <4.0.0"
dependencies:
  intl: ^0.19.0
  meta: ^1.9.1
  path: ^1.8.3
  yaml: ^3.1.2
dev_dependencies:
  flutter_lints: ^2.0.1
  test: ^1.16.8
